### ISSUE TITLE
Drop `ones(Tensor{order, dim})`

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/ContMechTensors.jl#101]
#100 implements `ones(T, dims...)`, with elements `one(T)` which means that we have one function `ones` that gives a tensor filled with 1, and another one that gives array with identity tensors. Should we just drop the function that gives a tensor filled with 1?

```jl
julia> ones(Tensor{2,2}) # Drop this?
2×2 ContMechTensors.Tensor{2,2,Float64,4}:
 1.0  1.0
 1.0  1.0

julia> ones(Tensor{2,2},1,1)
1×1 Array{ContMechTensors.Tensor{2,2,Float64,4},2}:
 [1.0 0.0; 0.0 1.0]
```

EDIT: If one really wants to create a tensor filled with ones it is easy to just create the tensor from a function:

```jl
julia> A = Tensor{2,2}((i,j)->1.0)
2×2 ContMechTensors.Tensor{2,2,Float64,4}:
 1.0  1.0
 1.0  1.0
```

**Comment by KristofferC** [comment]
How would you in a non allocating way get a tensor filled with ones then?

**Comment by KristofferC** [comment]
Ok, you can of course do it from a function but it will likely be quite slow and `ones` is the way that you do it for arrays so it feels like that is expected to work.

**Comment by KristofferC** [comment]
But yeah, it is a bit strange with `ones` meaning multiple things.

**Comment by fredrikekre** [comment]
We could just leave it as is. Just a bit weird.

It just feel like `ones(T, dims)` should give an array with elements `one(T)`.

**Comment by fredrikekre** [comment]
Could do this to get a non-allocating tensor with ones:

```jl
1.0 + zeros(Tensor{2, 2})
```

hehe

**Comment by fredrikekre** [comment]
But that's another discussion, perhaps `scalar + tensor` should not be allowed...

**Comment by KristofferC** [comment]
Perhaps not. Probably a quite unusual operation.

**Comment by fredrikekre** [comment]
Lets keep it as is and add a note in the docs.
