### ISSUE TITLE
Get SIMD working

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/ContMechTensors.jl#11]
Everything just uses scalar operations now. Depends on https://github.com/JuliaLang/julia/pull/15244 getting stable to use and merged.

**Comment by KristofferC** [comment]
It works when starting julia with `-O3`

**Comment by fredrikekre** [comment]
How much faster is it with SIMD? Now that we have benchmarking

**Comment by KristofferC** [comment]
I will run and check at some point :)
