### ISSUE TITLE
Conversion between dimensions

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/ContMechTensors.jl#32]
Should [this](https://github.com/KristofferC/ContMechTensors.jl/blob/master/src/promotion_conversion.jl#L47) type of conversion be allowed? I feel like thats not conversion since data may be lost, like this:

``` jl
julia> A = rand(Tensor{2,3})
3x3 ContMechTensors.Tensor{2,3,Float64,9}:
 0.966276   0.827608  0.561076
 0.748575   0.625611  0.932678
 0.0890943  0.858055  0.274502

julia> B = convert(Tensor{2,2},A)
2x2 ContMechTensors.Tensor{2,2,Float64,4}:
 0.966276  0.827608
 0.748575  0.625611

julia> C = convert(Tensor{2,3}, B)
3x3 ContMechTensors.Tensor{2,3,Float64,9}:
 0.966276  0.827608  0.0
 0.748575  0.625611  0.0
 0.0       0.0       0.0
```

If we truly converted the data I think A and C should be the same since you expect to get back what you started with when you convert back. Maybe we can have another function name for "converting" to a lower dimension, called `split` or something and one function called e.g. `extend` if a tensor with lower dimension should be extended with zeros in more dimensions? Similar as in #27 where converstion from a (non-symmetric) Tensor to a SymmetricTensor was removed.

**Comment by KristofferC** [comment]
Should probably be called `resize` or something.

``` jl
julia> a = rand(3)
re3-element Array{Float64,1}:
 0.808454
 0.178338
 0.683301

julia> resize!(a, 2)
2-element Array{Float64,1}:
 0.808454
 0.178338
```

**Comment by fredrikekre** [comment]
Does that function preserve the data?

``` jl
julia> a = rand(3)
3-element Array{Float64,1}:
 0.445738
 0.667952
 0.388141

julia> resize!(a,2);

julia> a
2-element Array{Float64,1}:
 0.445738
 0.667952

julia> resize!(a,3);

julia> a
3-element Array{Float64,1}:
 0.445738
 0.667952
 0.388141
```

**Comment by fredrikekre** [comment]
Nevermind, just extends the memory and the same value was stored there, right?

**Comment by fredrikekre** [comment]
``` jl
julia> a = rand(3)
3-element Array{Float64,1}:
 0.40551 
 0.110891
 0.114956

julia> resize!(a,5)
5-element Array{Float64,1}:
 0.40551     
 0.110891    
 0.114956    
 6.90951e-310
 6.90951e-310
```

**Comment by KristofferC** [comment]
> Nevermind, just extends the memory and the same value was stored there, right?

Exactly. Not guaranteed to preserve but in this type of cases it usually will

**Comment by fredrikekre** [comment]
But if we `resize` to a higher dimension, don't we wanna fill the new values with zeros? Instead of garbage values.

**Comment by KristofferC** [comment]
Yes. I mean, resize is a bit wrong as well... Resize keeps the type. This should return a new object with a new type.., That is why I used convert..  Tricky.

**Comment by fredrikekre** [comment]
You didn't like my idea with new function names?
- `extract`/`split` to convert to lower dimension
- `extend`/`expand` to convert to higher dimension

I just think it would be more clear what the function actually does :)

**Comment by KristofferC** [comment]
To make it type stable it needs to take the dimension as a type parameter and I don't see a clean way to do this. How would an actual function call look.

**Comment by fredrikekre** [comment]
Same as [this](https://github.com/KristofferC/ContMechTensors.jl/blob/master/src/tensor_ops.jl#L317)  , would return a new Tensor.

``` jl
julia> A3D = rand(Tensor{2,3})
3x3 ContMechTensors.Tensor{2,3,Float64,9}:
 0.461859  0.319096  0.0684431
 0.711956  0.565499  0.915405 
 0.230022  0.276082  0.600624 

julia> A2D = extract(Tensor{2,2}, A3D)
2x2 ContMechTensors.Tensor{2,2,Float64,4}:
 0.461859  0.319096
 0.711956  0.565499
```

**Comment by KristofferC** [comment]
Ah, okay. Should work.

**Comment by fredrikekre** [comment]
Are you on board with this? 
What should the function be called? Maybe the same no matter if the dimension goes up or down? `extend`? `expand`?

**Comment by KristofferC** [comment]
`convert`? XDDDD

`embed` to go from lower to higher maybe, like: https://en.wikipedia.org/wiki/Embedding

and then `project` or something to go to the lower dimension..?

**Comment by fredrikekre** [comment]
LUL its funny cause it makes sense!

`embed` and `project` sounds nice.

**Comment by fredrikekre** [comment]
+1 for removing it

**Comment by fredrikekre** [comment]
And also:

``` jl
julia> using BenchmarkTools, ContMechTensors

julia> A = rand(SymmetricTensor{2,3});

julia> B = convert(Tensor{2,3}, A)
3×3 ContMechTensors.Tensor{2,3,Float64,9}:
 0.706113  0.467037  0.932521
 0.467037  0.671132  0.92042 
 0.932521  0.92042   0.93085 

julia> @benchmark symmetric($B)
BenchmarkTools.Trial: 
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.489 ns (0.00% GC)
  median time:      3.499 ns (0.00% GC)
  mean time:        3.509 ns (0.00% GC)
  maximum time:     12.361 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark convert(SymmetricTensor{2,3},$B)
BenchmarkTools.Trial: 
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     26.945 ns (0.00% GC)
  median time:      26.959 ns (0.00% GC)
  mean time:        27.338 ns (0.00% GC)
  maximum time:     89.615 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     995
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

**Comment by KristofferC** [comment]
Yeah.. that's a bit bad..
