### ISSUE TITLE
doctests

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/ContMechTensors.jl#49]

**Comment by fredrikekre** [comment]
```
 !! Test error in the following code block in 'src/man/constructing_tensors.md':

        julia> SymmetricTensor{2,2}((i,j) -> i + j)
        2x2 ContMechTensors.SymmetricTensor{2,2,Int64,3}:
         2  3
         3  4

    in expression:

        SymmetricTensor{2,2}((i,j) -> i + j)

    expected:

        2x2 ContMechTensors.SymmetricTensor{2,2,Int64,3}:
         2  3
         3  4

    returned:

        2×2 ContMechTensors.SymmetricTensor{2,2,Int64,3}:
         2  3
         3  4

```

**Comment by fredrikekre** [comment]
Spot the difference...

**Comment by KristofferC** [comment]
Hmmm.....

**Comment by fredrikekre** [comment]
it passes with a blank line after...

**Comment by fredrikekre** [comment]
but others dont need a blank line... just this one

**Comment by fredrikekre** [comment]
HHAHHAHA
Its the x's that are different.

**Comment by fredrikekre** [comment]
in 2x2 or 2\times2 it seems like

**Comment by KristofferC** [comment]
lol

**Comment by KristofferC** [comment]
I see now

**Comment by KristofferC** [comment]
`× != x`

**Comment by fredrikekre** [comment]
yea, well, wonder where it originates from..

**Comment by fredrikekre** [comment]
closed by #50

**Comment by KristofferC** [comment]
https://travis-ci.org/KristofferC/ContMechTensors.jl/jobs/173401759#L194

The doctests right now only run in the "after success" part so failing doctests wont fail the build like they should. Hm.

**Comment by fredrikekre** [comment]
I dont think failing doctests fails the build.

**Comment by fredrikekre** [comment]
Travis didn't push the docs...

**Comment by KristofferC** [comment]
Because of the doctest crashing I presume.

**Comment by KristofferC** [comment]
https://ci.appveyor.com/project/KristofferC/contmechtensors-jl/build/1.0.20/job/6pkwpkrqvh1q0dom#L50

Wrecked by 32 bit Integers.

**Comment by fredrikekre** [comment]
Doesn't seem to error the tests anyway.
