### ISSUE TITLE
Restructure code

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/ContMechTensors.jl#59]
I would like to restructure the code. Currently it is quite messy.
I propose the following structure:

* `tensor_products.jl`: `dcontract`, `dot`, `tdot`, `otimes` and perhaps `cross`
* `nice_name.jl`: operations like `symmetric`, `transpose` etc. which permutes the input tensor. Name suggestion for file name?
* `other_operations.jl`: other operations, like `inv`, `det`, `trace`, `norm`
* `continuum_mech.jl`: `dev`, `mean`, `skew` ...
* `special_ops.jl`: specialized weird operations like `dotdot` etc.

Thoughts?

**Comment by fredrikekre** [comment]
Maybe `math_ops.jl` for inv, det, trace, norm which calculates something on a tensor.

**Comment by KristofferC** [comment]
Sure, I am also of the opinion that it is a bit messy.  Feel free to restructure as you see fit.
